### ISSUE TITLE
Primeiro diálogo com animação infinita

### ISSUE THREAD

**Issue by andremeireles** [kaiolabs/hells_castle#1]
Assim que começa o jogo, no primeiro diálogo com o mago, ao apertar qualquer botão de direção na última fala, faz com que o personagem entre em loop na animação de caminhar.

Aproveitando esse mesmo problema, se a janela for redimensionada, o personagem ultrapassa paredes e sai do foco da câmera.

No canto inferior esquerdo mostra as teclas que apertei, pra reproduzir o problema.

https://user-images.githubusercontent.com/1096931/180335564-b6e36438-57de-41a6-aed3-099215deed54.mp4

**Comment by kaiolabs** [comment]
Esse bug acontece quando o jogo e executado na web, se você jogar a versão dele para mobile você vera que isso não acontece.  Ele não foi feito pra se jogado na web, por conta disso acontece esses bugs.

**Comment by andremeireles** [comment]
Entendi.
Abri esse tópico porque pensei que fosse de sua preocupação que o jogo funcionasse corretamente na plataforma web.
Vou fechar a issue então.
